environments:
  - Staging
  - Production

settings:
  class_name: "AppConfig"

natrium_variables:
  DebugString: "debugString"

plists:
    "NatriumExampleManualProject/Info.plist":
        CFBundleDisplayName:
            Staging: App_staging
            Production: App

xcconfig:
    PRODUCT_BUNDLE_IDENTIFIER:
        Staging: com.esites.app.staging
        Production:
            Debug: com.esites.app.production
            Release: com.esites.app

variables:
    nilVariable: null
    testVariableDouble:
        Staging: 1.0
        Production: 5.5

    testVariableString:
        Staging,Production:
            Debug: "#{DebugString}"
            Release: "releaseString"
    testVariableBoolean: false
    testVariableInteger: 125

files:
  Files/file.html:
    Staging: Files/file-staging.html
    Production: Files/file-production.html

appicon:
    original: icon.png
    appiconset: NatriumExampleManualProject/Assets.xcassets/AppIcon.appiconset/
    idioms:
      - iphone
      - ipad
    ribbon:
        Production:
          Debug: "PRODUCTION"
          Release: ""
        Staging: "STAGING"


target_specific:
  NatriumExampleManualProject:
    variables:
      testVariableString: "Target #2"
    plists:
      "NatriumExampleManualProject/Info.plist":
        CFBundleDisplayName: "App #2"

launch_screen_versioning:
    path: NatriumExampleManualProject/Base.lproj/LaunchScreen.storyboard
    labelName: LaunchScreenVersionLabel
    enabled: true
